### ISSUE TITLE
SDA-ADMIN CLI tool

### ISSUE THREAD

**Issue by jbygdell** [neicnordic/sensitive-data-archive#1004] opened 2024-08-23 08:56 UTC
**Please describe the feature**
As a repository admin, I want a tool so that I don't have to use `curl` + `jq` in a bash script.

**Acceptance criteria**
- [ ] A tool similar to `sda-cli` to facilitate interaction with the admin API
- [ ] Tests verifying the changes are added

**Additional context**

**Estimation of size**: medium

**Estimation of priority**: medium

**Comment by aaperis** [comment] 2024-08-28 07:46
duplicate of #1007

**Closed by aaperis** 2024-08-28 07:47 UTC
