### ISSUE TITLE
[s3inbox] Migrate from `github.com/aws/aws-sdk-go` to `github.com/aws/aws-sdk-go-v2`

### ISSUE THREAD

**Issue by jbygdell** [neicnordic/sensitive-data-archive#530] opened 2023-12-13 09:10 UTC
**Please describe the feature**
As a developer, I want the code to use the latest version of a module so that we can make use of the new functionality and security options.

**Acceptance criteria**
- [ ] De-duplicate code that already exists in `internal/storage`
- [ ] Tests verifying the changes are added

**Additional context**

**Estimation of size**: medium
**Estimation of priority**: medium

**Comment by ahembal** [comment] 2024-01-18 12:51
is that issue duplicate of https://github.com/neicnordic/sensitive-data-archive/issues/529 ?

**Closed** 2024-02-08 07:06 UTC
