### ISSUE TITLE
[sda-download] Refactor/make sure we always set appropriate status on failure

### ISSUE THREAD

**Issue by pontus** [neicnordic/sensitive-data-archive#747] opened 2024-03-14 07:29 UTC
Currently it's not clear where failures should be signaled to the client, and difficult from reading the code to be sure we always signal appropriately. This could probably be improved.

This is duplicate of #697 and will be addressed there.

**Comment by viklund** [comment] 2024-05-15 08:06
Duplicate of #697

**Closed by viklund** 2024-05-15 08:06 UTC
Labels: Refactoring
